name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pr-validation:
    name: test-${{ matrix.os }}-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          path: substrafl

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - if: startsWith(matrix.os, 'ubuntu') == true
        name: Free disk space
        run: |
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - if: startsWith(matrix.os, 'windows') == true
        name: Switch Daemon
        run: |
          Install-WindowsFeature -Name Hyper-V,Containers -IncludeAllSubFeature -IncludeManagementTools
          [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
          cd C:\Windows\system32
          $configfile = @"

          {

            "experimental": true

          }

          "@
          $configfile|Out-File -FilePath C:\ProgramData\docker\config\daemon.json -Encoding ascii -Force
          C:\Program Files\Linux Containers
          Invoke-WebRequest -Uri "https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip" -UseBasicParsing -OutFile release.zip
          Expand-Archive release.zip -DestinationPath “$Env:ProgramFiles\Linux Containers\.”
          Restart-Service docker

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v3
        with:
          repository: substra/substra-tools
          path: substratools

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v3
        with:
          repository: substra/substra
          path: substra

      - uses: actions/cache@v3.0.8
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('substrafl/setup.py') }}-${{ hashFiles  ('substrafl/docs/requirements.txt') }}-${{ hashFiles('substrafl/benchmark/camelyon/requirements.txt') }}

      - name: Install package
        run: |
          pip install --upgrade -e substrafl[dev]
          pip install --upgrade -e substra
          pip install --upgrade -e substratools

      - name: Run the slow local tests
        env:
          USE_LATEST_SUBSTRATOOLS: True
        run: |
          cd substrafl
          make COV_OPTIONS="--cov=substrafl --cov-append --cov-report=html:htmlcov" test-local-slow

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: substrafl/htmlcov
