name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pr-validation:
    name: test-${{ matrix.os }}-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          path: substrafl

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Free disk space
        run: |
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v4
        with:
          repository: substra/substra-tools
          path: substratools

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v4
        with:
          repository: substra/substra
          path: substra

      - uses: actions/cache@v3.0.8
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('substrafl/pyproject.toml') }}-${{ hashFiles  ('substrafl/docs/requirements.txt') }}-${{ hashFiles('substrafl/benchmark/camelyon/requirements.txt') }}

      - name: Install package
        run: |
          pip install --upgrade pip
          pip install --upgrade -e substrafl[dev]
          pip install --upgrade -e substra
          pip install --upgrade -e substratools

      - name: Run the slow local tests
        run: |
          cd substrafl
          make COV_OPTIONS="--cov=substrafl --cov-append --cov-report=html:htmlcov" PRUNE_OPTIONS="--prune-docker" test-local-slow

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: substrafl/htmlcov
