name: pr-validation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pr-validation:
    name: test-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python: ['3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
        with:
          path: connectlib
          lfs: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure docker for GCP
        run: gcloud auth configure-docker
        shell: bash

      - name: Install lint checks
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir pytest black flake8
          pip install --no-cache-dir pre-commit

      - name: Code conventions
        run: |
          cd connectlib
          pre-commit run --all-files

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v2
        with:
          repository: owkin/connect-tools
          token: ${{ secrets.ACCESS_TOKEN }}
          path: substratools

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v2
        with:
          repository: owkin/substra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: substra

      - name: Login pypi
        run: |
             mkdir ~/.pip || touch ~/.pip/pip.conf
             echo "[global]" >> ~/.pip/pip.conf
             echo "extra-index-url = https://connectors-service-account:${{ secrets.TWINE_PASSWORD }}@pypi.owkin.com/simple" >> ~/.pip/pip.conf

      - name: Install package
        run: |
             pip install --no-cache-dir -e substra
             pip install --no-cache-dir -e substratools
             pip install --no-cache-dir -e connectlib[dev]

      - name: Install package for tests
        run: |
             cd connectlib/tests/dependency/installable_library
             pip install --no-cache-dir -e .

      - name: Run tests
        run: |
          cd connectlib
          make COV_OPTIONS="--cov=connectlib --cov-append --cov-report=html:htmlcov" test-local

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: connectlib/htmlcov

  pr-validation-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Login pypi
        run: |
             mkdir ~/.pip || touch ~/.pip/pip.conf
             echo "[global]" >> ~/.pip/pip.conf
             echo "extra-index-url = https://connectors-service-account:${{ secrets.TWINE_PASSWORD }}@pypi.owkin.com/simple" >> ~/.pip/pip.conf

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir .[dev]
          pip install --no-cache-dir -r docs/requirements.txt

      - name: Test docs
        run: |
          cd docs
          make clean html
