name: pr-validation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pr-validation:
    name: test-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python: ['3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v3
        with:
          path: connectlib
          lfs: true

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/cache@v3.0.2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install lint checks
        run: |
          pip install --upgrade pip
          pip install --upgrade pytest black flake8 pre-commit

      - name: Code conventions
        run: |
          cd connectlib
          pre-commit run --all-files

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v3
        with:
          repository: owkin/connect-tools
          token: ${{ secrets.ACCESS_TOKEN }}
          path: substratools

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v3
        with:
          repository: owkin/substra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: substra

      # Some tests install the libraries from the PyPi
      - name: Login pypi
        run: |
             mkdir ~/.pip || touch ~/.pip/pip.conf
             echo "[global]" >> ~/.pip/pip.conf
             echo "extra-index-url = https://connectors-service-account:${{ secrets.TWINE_PASSWORD }}@pypi.owkin.com/simple" >> ~/.pip/pip.conf

      - name: Install package
        run: |
             pip install --upgrade -e substra
             pip install --upgrade -e substratools
             pip install --upgrade -e connectlib[dev]

      - name: Run the fast local tests
        run: |
          cd connectlib
          make COV_OPTIONS="--cov=connectlib --cov-append --cov-report=html:htmlcov" test-local-fast

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: connectlib/htmlcov

  pr-validation-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Login pypi
        run: |
             mkdir ~/.pip || touch ~/.pip/pip.conf
             echo "[global]" >> ~/.pip/pip.conf
             echo "extra-index-url = https://connectors-service-account:${{ secrets.TWINE_PASSWORD }}@pypi.owkin.com/simple" >> ~/.pip/pip.conf

      - uses: actions/cache@v3.0.2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        run: |
          pip install --upgrade .[dev]
          pip install --upgrade -r docs/requirements.txt

      - name: Test docs
        run: |
          cd docs
          make clean html
