name: pr-validation
on:
  pull_request:
    branches:
      - "main"

jobs:
  pr-validation:
    name: test-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install lint checks
        run: pip install pytest black flake8

      - name: Code conventions
        run: |
          flake8 connectlib
          black --check .

      - name: Install package
        run: pip install -e '.[dev]'

      - name: Run tests
        run: pytest --cov=connectlib --cov-append --cov-report=html:htmlcov

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: htmlcov

  pr-validation-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: pip install -r docs/requirements.txt

      - name: Test docs
        run: |
          cd docs
          make html
