name: windows-subprocess-check
on:
  push:
    branches:
      - main

jobs:
  pr-validation:
    name: test-${{ matrix.os }}-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          path: substrafl

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v3
        with:
          repository: substra/substra-tools
          path: substratools

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v3
        with:
          repository: substra/substra
          path: substra

      - uses: actions/cache@v3.0.8
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('substrafl/pyproject.toml') }}-${{ hashFiles  ('substrafl/docs/requirements.txt') }}-${{ hashFiles('substrafl/benchmark/camelyon/requirements.txt') }}

      - name: Install package
        run: |
          pip install --upgrade -e substrafl[dev]
          pip install --upgrade -e substra
          pip install --upgrade -e substratools

      - name: Run the subprocess tests
        run: |
          cd substrafl
          make COV_OPTIONS="--cov=substrafl --cov-append --cov-report=html:htmlcov" test-subprocess

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: substrafl/htmlcov
